# base image
FROM node:18-slim

# set working directory
WORKDIR /app

# copy package files and install
COPY package*.json ./
RUN npm install --production

# copy your compiled server code
COPY . .

# expose port and start the server
EXPOSE 8080
CMD [ "npm", "run", "start:server" ]